### ISSUE TITLE
Express 환경 세팅

### ISSUE THREAD

**Issue by ye-seob** [ye-seob/Hackerton#1]
## To-do

- [x] index.js 설정
- [x] 환경 변수 설정
- [x] nodemon 설정
- [x] module.js 설정
